# Generated by Django 4.0.2 on 2022-02-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_videosname_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='body',
            new_name='replyBody',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='index',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='videosname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
