# Generated by Django 4.0.2 on 2022-02-10 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_rename_body_reply_replybody_rename_index_reply_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosname',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 6, 2, 32, 917711, tzinfo=utc)),
        ),
    ]
