# Generated by Django 4.0.2 on 2022-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_videosname_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosname',
            name='uploadDate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
